version: "3.8"

services:
  backend:
    build: .
    container_name: internbank-backend
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://internbank.database.windows.net:1433;database=internbank;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: internbank-db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: internbank-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
